language: c

# Make sure build dependencies are installed.
install:
 - sudo apt-get update && sudo apt-get install nunit mono-gmcs cli-common-dev libgl1-mesa-dev libsdl1.2-dev libopenal-dev

before_script:
  - export QINIU_ACCESS_KEY="IT9iP3J9wdXXYsT1p8ns0gWD-CQOdLvIQuyE0FOK"
  - export QINIU_SECRET_KEY="zUCzekBtEqTZ4-WJPCGlBrr2PeyYxsYn98LPaivM"
  - export QINIU_TEST_BUCKET="icattlecoder3"
  - export QINIU_TEST_DOMAIN="qiniuphotos.qiniudn.com" 

script:
 - make
 - make test
